name: berber_utils
description: Berber platformu için utility fonksiyonlar, extensionlar, controllerler ve widgetler
version: 0.0.1
homepage: https://github.com/berber2425/berber_utils

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  path: ^1.8.0
  http: ^1.1.0
  url_launcher: ^6.1.0
  share_plus: ^7.2.0
  image_picker: ^1.0.0
  file_picker: ^6.1.0
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.0
  connectivity_plus: ^5.0.0
  package_info_plus: ^5.0.0
  device_info_plus: ^9.0.0
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0
  logger: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
